# -*- coding: utf-8 -*-
"""cine-ingressos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ww1JUGkRSSR3e--CfsIbsaM851XG8-g4
"""

from re import L
print("Seja bem vindo à bilheteria do cinema!")

idade = int(input("Digite sua idade: "))

filme_infantil = ("Rei Leão")
filme_adolescente = ("Percy Jackson")
filme_adulto = ("A hipótese do amor")

if idade < 12:
    print("Recomendação: ", filme_infantil)
elif  12 <= idade < 18:
    print("Recomendação: ", filme_adolescente)
else:
    print("Recomendação: ", filme_adulto)

quantidade_disponivel = 10

escolha_ingressos = int(input("Quantos ingressos você vai querer? "))

if escolha_ingressos > quantidade_disponivel:
  print("Ingressos indisponíveis. Quantidades disponíveis: ", quantidade_disponivel)
elif escolha_ingressos <= 0:
  print("Quantidade inválida.")
else:
  print("Ingressos disponíveis!")